version: "3.7"
services:
  backend:
    build: 
      context: api
    ports: 
      - 4000:4000
  frontend:
    build:
      context: app
    privileged: true
    ports: 
      - 3000:3000
  database:
    image: dgraph/standalone:v21.03.1
    volumes: 
      - db-data:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
      - 8000:8000
volumes:
  db-data: